baseURL = "https://neutronimaging-dev.pages.ornl.gov/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = ""
  description = "ORNL Neutron Imaging for Users Home Page"
  author = "Jean Bilheux"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github Repos"
url = "github"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Showcases"
url = "/showcase"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-user-circle'></i> Contacts"
url = "credits"
weight = 30

[Languages.fr]
title = "Site pour les usagers de la ligne de faisceau d'imagerie d'ORNL"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Repos. Github"
identifier = "ds"
url = "github"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Contactes"
url = "credits"
weight = 30

[Languages.es]
title = "web site para los pequinos de la imaga"
weight = 2
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Repos. Github"
identifier = "ds"
url = "github"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Contactes"
url = "credits"
weight = 30